import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Plus, Download, Trash2 } from "lucide-react";
import type { Tables } from "@/integrations/supabase/types";

const PHASES = ["Blankspace", "Blueprint", "Build", "Bridge", "Beyond"] as const;
const MODULES = ["Presence™", "Flow™", "Connect™", "Insights™", "Growth™"];

export const Route = createFileRoute("/_authenticated/partners")({
  head: () => ({
    meta: [
      { title: "Partners — Third Room HQ" },
      { name: "description", content: "Partner system register: phases, health, active modules." },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: PartnersPage,
});

function PartnersPage() {
  const qc = useQueryClient();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ brand_name: "", contact_email: "", current_phase: "Blankspace", active_modules: [] as string[] });

  const { data: partners = [] } = useQuery({
    queryKey: ["partners"],
    queryFn: async () => {
      const { data } = await supabase.from("partners").select("*").order("created_at", { ascending: false });
      return (data ?? []) as Tables<"partners">[];
    },
  });

  const createPartner = useMutation({
    mutationFn: async () => {
      const { error } = await supabase.from("partners").insert({
        brand_name: form.brand_name,
        contact_email: form.contact_email || null,
        current_phase: form.current_phase,
        active_modules: form.active_modules,
        health_score: Math.floor(Math.random() * 30) + 60,
      });
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Partner added");
      setOpen(false);
      setForm({ brand_name: "", contact_email: "", current_phase: "Blankspace", active_modules: [] });
      qc.invalidateQueries({ queryKey: ["partners"] });
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  async function updatePhase(id: string, phase: string) {
    await supabase.from("partners").update({ current_phase: phase }).eq("id", id);
    qc.invalidateQueries({ queryKey: ["partners"] });
  }

  async function remove(id: string) {
    await supabase.from("partners").delete().eq("id", id);
    qc.invalidateQueries({ queryKey: ["partners"] });
  }

  function generateArchitecture(p: Tables<"partners">) {
    const doc = `# ${p.brand_name} — Business Architecture v1.0

**Contact:** ${p.contact_email ?? "—"}
**Current Phase:** ${p.current_phase}
**Health Score:** ${p.health_score}/100
**Active Modules:** ${(p.active_modules ?? []).join(", ") || "None yet"}

## Customer Journey Map
1. Discovery — Presence™ layer
2. Engagement — Flow™ layer
3. Conversion — Connect™ layer
4. Retention — Insights™ layer
5. Expansion — Growth™ layer

## Tech Stack
- CRM & CMS
- Automation webhooks
- Analytics & reporting

## Notes
${p.notes ?? "—"}

_Generated by Third Room HQ — ${new Date().toLocaleDateString()}_
`;
    const blob = new Blob([doc], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${p.brand_name.replace(/\s+/g, "-")}-architecture-v1.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Module 07</p>
          <h1 className="mt-1 font-display text-4xl">Partner Register</h1>
        </div>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button className="gap-2"><Plus className="h-4 w-4" /> Add partner</Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader><DialogTitle>New partner</DialogTitle></DialogHeader>
            <div className="space-y-3">
              <Input placeholder="Brand name" value={form.brand_name} onChange={(e) => setForm({ ...form, brand_name: e.target.value })} />
              <Input placeholder="Contact email" value={form.contact_email} onChange={(e) => setForm({ ...form, contact_email: e.target.value })} />
              <Select value={form.current_phase} onValueChange={(v) => setForm({ ...form, current_phase: v })}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {PHASES.map((p) => <SelectItem key={p} value={p}>{p}™</SelectItem>)}
                </SelectContent>
              </Select>
              <div className="flex flex-wrap gap-2">
                {MODULES.map((m) => {
                  const active = form.active_modules.includes(m);
                  return (
                    <button key={m}
                      onClick={() => setForm({ ...form, active_modules: active ? form.active_modules.filter(x => x !== m) : [...form.active_modules, m] })}
                      className={`rounded-full border px-3 py-1 text-xs ${active ? "border-charcoal bg-charcoal text-offwhite" : "border-border text-muted-foreground"}`}
                    >{m}</button>
                  );
                })}
              </div>
              <Button onClick={() => createPartner.mutate()} disabled={!form.brand_name || createPartner.isPending} className="w-full">
                Create partner
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </header>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {partners.map((p) => (
          <article key={p.id} className="rounded-2xl border border-border bg-card p-5 shadow-card">
            <div className="flex items-start justify-between">
              <div>
                <h3 className="font-display text-xl">{p.brand_name}</h3>
                <p className="text-xs text-muted-foreground">{p.contact_email ?? "—"}</p>
              </div>
              <span className="rounded-full bg-stone-warm px-2 py-0.5 text-xs font-semibold text-charcoal">{p.health_score}</span>
            </div>

            <div className="mt-4">
              <p className="text-[10px] uppercase tracking-wider text-muted-foreground">Phase</p>
              <Select value={p.current_phase} onValueChange={(v) => updatePhase(p.id, v)}>
                <SelectTrigger className="mt-1 h-8"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {PHASES.map((ph) => <SelectItem key={ph} value={ph}>{ph}™</SelectItem>)}
                </SelectContent>
              </Select>
            </div>

            {p.active_modules && p.active_modules.length > 0 && (
              <div className="mt-3 flex flex-wrap gap-1">
                {p.active_modules.map((m) => (
                  <span key={m} className="rounded bg-muted px-2 py-0.5 text-[10px]">{m}</span>
                ))}
              </div>
            )}

            <div className="mt-4 flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={() => generateArchitecture(p)} className="gap-1">
                <Download className="h-3 w-3" /> Architecture doc
              </Button>
              <Button variant="ghost" size="sm" onClick={() => remove(p.id)} className="text-destructive">
                <Trash2 className="h-3 w-3" />
              </Button>
            </div>
          </article>
        ))}
        {partners.length === 0 && (
          <p className="text-sm text-muted-foreground">No partners yet.</p>
        )}
      </div>
    </div>
  );
}
